# Generated by Django 3.2.5 on 2023-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
