# Generated by Django 3.2.5 on 2023-10-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_feed_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='message',
            field=models.CharField(max_length=20),
        ),
    ]
