# Generated by Django 3.2.5 on 2023-10-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_feed_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('speed', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available')], max_length=20)),
            ],
        ),
    ]
