# Generated by Django 3.2.5 on 2023-11-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
    ]
