# Generated by Django 3.2.5 on 2023-12-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20231201_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='license_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
