# Generated by Django 3.2.5 on 2023-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_pay_license_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contact',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='contact',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
