# Generated by Django 3.2.5 on 2023-12-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20231205_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='qr_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
