# Generated by Django 3.2.5 on 2023-12-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_pay_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
