# Generated by Django 3.2.5 on 2023-12-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_alter_pay_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='qr_code',
        ),
    ]
