# Generated by Django 3.2.5 on 2023-12-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_remove_pay_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
